# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/mainwindow.ui'
#
# Created: Wed Mar 15 18:51:51 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 853)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.site_label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.site_label.setFont(font)
        self.site_label.setText("")
        self.site_label.setAlignment(QtCore.Qt.AlignCenter)
        self.site_label.setObjectName("site_label")
        self.verticalLayout_4.addWidget(self.site_label)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.scrollArea.setPalette(palette)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.reportArea = QtGui.QWidget()
        self.reportArea.setGeometry(QtCore.QRect(0, 0, 248, 637))
        self.reportArea.setObjectName("reportArea")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.reportArea)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.scrollArea.setWidget(self.reportArea)
        self.verticalLayout_4.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.patients_details_dockwidget = QtGui.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.patients_details_dockwidget.setFont(font)
        self.patients_details_dockwidget.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.patients_details_dockwidget.setObjectName("patients_details_dockwidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget = QtGui.QTreeWidget(self.dockWidgetContents)
        self.treeWidget.setProperty("showDropIndicator", True)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setRootIsDecorated(False)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.patients_details_dockwidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.patients_details_dockwidget)
        self.parameters_dockwidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parameters_dockwidget.sizePolicy().hasHeightForWidth())
        self.parameters_dockwidget.setSizePolicy(sizePolicy)
        self.parameters_dockwidget.setMinimumSize(QtCore.QSize(560, 681))
        self.parameters_dockwidget.setFloating(False)
        self.parameters_dockwidget.setAllowedAreas(QtCore.Qt.NoDockWidgetArea)
        self.parameters_dockwidget.setObjectName("parameters_dockwidget")
        self.parameters_dockcontents = QtGui.QWidget()
        self.parameters_dockcontents.setObjectName("parameters_dockcontents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.parameters_dockcontents)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_3.setContentsMargins(-1, 12, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtGui.QGroupBox(self.parameters_dockcontents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fuchiadb_path_lineedit = QtGui.QLineEdit(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.fuchiadb_path_lineedit.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.fuchiadb_path_lineedit.setFont(font)
        self.fuchiadb_path_lineedit.setReadOnly(True)
        self.fuchiadb_path_lineedit.setObjectName("fuchiadb_path_lineedit")
        self.horizontalLayout_2.addWidget(self.fuchiadb_path_lineedit)
        self.browse_button = QtGui.QToolButton(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.browse_button.setFont(font)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout_2.addWidget(self.browse_button)
        self.formLayout.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.site_nameedit = QtGui.QLineEdit(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.site_nameedit.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.site_nameedit.setFont(font)
        self.site_nameedit.setReadOnly(True)
        self.site_nameedit.setObjectName("site_nameedit")
        self.horizontalLayout_4.addWidget(self.site_nameedit)
        self.change_name_button = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.change_name_button.setFont(font)
        self.change_name_button.setObjectName("change_name_button")
        self.horizontalLayout_4.addWidget(self.change_name_button)
        self.formLayout.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_9 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.region_nameedit = QtGui.QLineEdit(self.groupBox)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.region_nameedit.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.region_nameedit.setFont(font)
        self.region_nameedit.setReadOnly(True)
        self.region_nameedit.setObjectName("region_nameedit")
        self.horizontalLayout_9.addWidget(self.region_nameedit)
        self.change_region_button = QtGui.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.change_region_button.setFont(font)
        self.change_region_button.setObjectName("change_region_button")
        self.horizontalLayout_9.addWidget(self.change_region_button)
        self.formLayout.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.advanced_parameters_button = QtGui.QPushButton(self.parameters_dockcontents)
        self.advanced_parameters_button.setObjectName("advanced_parameters_button")
        self.horizontalLayout.addWidget(self.advanced_parameters_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.line = QtGui.QFrame(self.parameters_dockcontents)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.advanced_frame = QtGui.QFrame(self.parameters_dockcontents)
        self.advanced_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.advanced_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.advanced_frame.setObjectName("advanced_frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.advanced_frame)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, -1, 10)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.modify_advanced_pushbutton = QtGui.QPushButton(self.advanced_frame)
        self.modify_advanced_pushbutton.setCheckable(True)
        self.modify_advanced_pushbutton.setAutoExclusive(False)
        self.modify_advanced_pushbutton.setObjectName("modify_advanced_pushbutton")
        self.horizontalLayout_10.addWidget(self.modify_advanced_pushbutton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.pdv_group = QtGui.QGroupBox(self.advanced_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.pdv_group.setFont(font)
        self.pdv_group.setObjectName("pdv_group")
        self.formLayout_2 = QtGui.QFormLayout(self.pdv_group)
        self.formLayout_2.setContentsMargins(-1, 12, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtGui.QLabel(self.pdv_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.pdv_delay_spin = QtGui.QSpinBox(self.pdv_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.pdv_delay_spin.setFont(font)
        self.pdv_delay_spin.setObjectName("pdv_delay_spin")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.pdv_delay_spin)
        self.label_4 = QtGui.QLabel(self.pdv_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.default_visit_offset_spin = QtGui.QSpinBox(self.pdv_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.default_visit_offset_spin.setFont(font)
        self.default_visit_offset_spin.setObjectName("default_visit_offset_spin")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.default_visit_offset_spin)
        self.verticalLayout_5.addWidget(self.pdv_group)
        self.treatment_group = QtGui.QGroupBox(self.advanced_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.treatment_group.setFont(font)
        self.treatment_group.setObjectName("treatment_group")
        self.formLayout_3 = QtGui.QFormLayout(self.treatment_group)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_5 = QtGui.QLabel(self.treatment_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.non_arv_lineedit = QtGui.QLineEdit(self.treatment_group)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.non_arv_lineedit.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.non_arv_lineedit.setFont(font)
        self.non_arv_lineedit.setReadOnly(True)
        self.non_arv_lineedit.setObjectName("non_arv_lineedit")
        self.horizontalLayout_5.addWidget(self.non_arv_lineedit)
        self.modify_non_arv_button = QtGui.QPushButton(self.treatment_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.modify_non_arv_button.setFont(font)
        self.modify_non_arv_button.setObjectName("modify_non_arv_button")
        self.horizontalLayout_5.addWidget(self.modify_non_arv_button)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_6 = QtGui.QLabel(self.treatment_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ctx_lineedit = QtGui.QLineEdit(self.treatment_group)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.ctx_lineedit.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.ctx_lineedit.setFont(font)
        self.ctx_lineedit.setReadOnly(True)
        self.ctx_lineedit.setObjectName("ctx_lineedit")
        self.horizontalLayout_6.addWidget(self.ctx_lineedit)
        self.modify_ctx_button = QtGui.QPushButton(self.treatment_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.modify_ctx_button.setFont(font)
        self.modify_ctx_button.setObjectName("modify_ctx_button")
        self.horizontalLayout_6.addWidget(self.modify_ctx_button)
        self.formLayout_3.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.verticalLayout_5.addWidget(self.treatment_group)
        self.tb_group = QtGui.QGroupBox(self.advanced_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.tb_group.setFont(font)
        self.tb_group.setObjectName("tb_group")
        self.formLayout_4 = QtGui.QFormLayout(self.tb_group)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_7 = QtGui.QLabel(self.tb_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.entry_tb_lineedit = QtGui.QLineEdit(self.tb_group)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.entry_tb_lineedit.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.entry_tb_lineedit.setFont(font)
        self.entry_tb_lineedit.setReadOnly(True)
        self.entry_tb_lineedit.setObjectName("entry_tb_lineedit")
        self.horizontalLayout_7.addWidget(self.entry_tb_lineedit)
        self.modify_entry_tb_button = QtGui.QPushButton(self.tb_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.modify_entry_tb_button.setFont(font)
        self.modify_entry_tb_button.setObjectName("modify_entry_tb_button")
        self.horizontalLayout_7.addWidget(self.modify_entry_tb_button)
        self.formLayout_4.setLayout(0, QtGui.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.label_8 = QtGui.QLabel(self.tb_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.diag_tb_lineedit = QtGui.QLineEdit(self.tb_group)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(139, 139, 139))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(97, 97, 97))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(240, 240, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        self.diag_tb_lineedit.setPalette(palette)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.diag_tb_lineedit.setFont(font)
        self.diag_tb_lineedit.setReadOnly(True)
        self.diag_tb_lineedit.setObjectName("diag_tb_lineedit")
        self.horizontalLayout_8.addWidget(self.diag_tb_lineedit)
        self.modify_diag_tb_button = QtGui.QPushButton(self.tb_group)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setBold(False)
        self.modify_diag_tb_button.setFont(font)
        self.modify_diag_tb_button.setObjectName("modify_diag_tb_button")
        self.horizontalLayout_8.addWidget(self.modify_diag_tb_button)
        self.formLayout_4.setLayout(1, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.verticalLayout_5.addWidget(self.tb_group)
        self.verticalLayout_3.addWidget(self.advanced_frame)
        self.parameters_dockwidget.setWidget(self.parameters_dockcontents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.parameters_dockwidget)
        self.toolbar = QtGui.QToolBar(MainWindow)
        self.toolbar.setObjectName("toolbar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolbar)
        self.data_dockwidget = QtGui.QDockWidget(MainWindow)
        self.data_dockwidget.setObjectName("data_dockwidget")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.data_table = QtGui.QTableWidget(self.dockWidgetContents_3)
        self.data_table.setObjectName("data_table")
        self.data_table.setColumnCount(0)
        self.data_table.setRowCount(0)
        self.verticalLayout.addWidget(self.data_table)
        self.data_dockwidget.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.data_dockwidget)
        self.prescriptions_dockwidget = QtGui.QDockWidget(MainWindow)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.prescriptions_dockwidget.setFont(font)
        self.prescriptions_dockwidget.setObjectName("prescriptions_dockwidget")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.arv_presc_treeWidget = QtGui.QTreeWidget(self.dockWidgetContents_2)
        self.arv_presc_treeWidget.setProperty("showDropIndicator", True)
        self.arv_presc_treeWidget.setAlternatingRowColors(True)
        self.arv_presc_treeWidget.setRootIsDecorated(False)
        self.arv_presc_treeWidget.setHeaderHidden(False)
        self.arv_presc_treeWidget.setObjectName("arv_presc_treeWidget")
        self.arv_presc_treeWidget.headerItem().setText(0, "1")
        self.verticalLayout_6.addWidget(self.arv_presc_treeWidget)
        self.prescriptions_dockwidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.prescriptions_dockwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Génération de rapports mensuel à partir d\'une base Fuchia", None, QtGui.QApplication.UnicodeUTF8))
        self.patients_details_dockwidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Détail des codes patients", None, QtGui.QApplication.UnicodeUTF8))
        self.parameters_dockwidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Paramètres", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Base de données", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Base Fuchia à inspecter", None, QtGui.QApplication.UnicodeUTF8))
        self.browse_button.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Nom du site", None, QtGui.QApplication.UnicodeUTF8))
        self.change_name_button.setText(QtGui.QApplication.translate("MainWindow", "Changer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Nom de la région", None, QtGui.QApplication.UnicodeUTF8))
        self.change_region_button.setText(QtGui.QApplication.translate("MainWindow", "Changer", None, QtGui.QApplication.UnicodeUTF8))
        self.advanced_parameters_button.setText(QtGui.QApplication.translate("MainWindow", "Montrer les paramètres avancés", None, QtGui.QApplication.UnicodeUTF8))
        self.modify_advanced_pushbutton.setText(QtGui.QApplication.translate("MainWindow", "Modifier les paramètres avancés", None, QtGui.QApplication.UnicodeUTF8))
        self.pdv_group.setTitle(QtGui.QApplication.translate("MainWindow", "Détection des perdus de vue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Délai (en mois) après la date de rdv pour les pdv", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Délai par défaut (en mois) entre deux visites", None, QtGui.QApplication.UnicodeUTF8))
        self.treatment_group.setTitle(QtGui.QApplication.translate("MainWindow", "Traitements", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Médicaments non ARV", None, QtGui.QApplication.UnicodeUTF8))
        self.modify_non_arv_button.setText(QtGui.QApplication.translate("MainWindow", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Traitement(s) cotrimoxazole", None, QtGui.QApplication.UnicodeUTF8))
        self.modify_ctx_button.setText(QtGui.QApplication.translate("MainWindow", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.tb_group.setTitle(QtGui.QApplication.translate("MainWindow", "Tuberculose", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Type(s) d\'entrée(s) Tb", None, QtGui.QApplication.UnicodeUTF8))
        self.modify_entry_tb_button.setText(QtGui.QApplication.translate("MainWindow", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Diagnostic(s) Tb", None, QtGui.QApplication.UnicodeUTF8))
        self.modify_diag_tb_button.setText(QtGui.QApplication.translate("MainWindow", "Modifier", None, QtGui.QApplication.UnicodeUTF8))
        self.toolbar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.data_dockwidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Tableau de données", None, QtGui.QApplication.UnicodeUTF8))
        self.prescriptions_dockwidget.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Prescriptions ARV", None, QtGui.QApplication.UnicodeUTF8))

